### ISSUE TITLE
Album covers written to file tag aren't displayed 

### ISSUE THREAD

**Issue by jhoc2000** [vanilla-music/vanilla-music-cover-fetch#17] opened 2020-10-28 04:07 UTC
I have found that when looking at the "Now playing" screen of Vanilla Music, the previously album cover, saved to file tag, doesn't display. I've tried forcing Vanilla Music to close but the same problem occurs. Here's how I found the issue:

1. I've downloaded the album and stored the m4a files into a dedicated folder on the SDCard.

2. I then do a "metadata fetcher" to download the metadata and stored it in the tag file.

3. I then use cover fetcher to download the album image. Sometimes the wrong cover is displayed for different songs so I also stored the album image into the music folder as folder.jpg. When I look at the songs in that folder the right album cover thumbnail is displayed:

![Screenshot_20201028-150354_Vanilla_Music](https://user-images.githubusercontent.com/16982707/97389723-26cc1b80-192f-11eb-898a-25a416b7d79b.png)

4. I then repeat cover fetcher for those songs that have the wrong album image. 

5. I then use the folder icon in cover fetcher to choose the image (folder.jpg) in the folder and then write that to the file tag.

6. When I next play that song no cover or the wrong cover is displayed. It appears that writing to the file tag either doesn't work or doesn't override the original cover fetch. 
![Screenshot_20201028-150445_Vanilla_Music](https://user-images.githubusercontent.com/16982707/97389750-3b101880-192f-11eb-94c0-9d66269da61a.png)

**Comment by Kaned1as** [comment] 2020-10-30 17:44
It works. But Vanilla Music doesn't refresh the metadata of the file until it is restarted. See https://github.com/vanilla-music/vanilla/pull/881

**Comment by Kaned1as** [comment] 2020-10-30 17:44
Duplicate of https://github.com/vanilla-music/vanilla/issues/879

**Closed as completed by Kaned1as** 2020-10-30 17:44 UTC

**Comment by jhoc2000** [comment] 2020-10-30 23:21
Ah yes. I did a rescan of the media library in Vanilla Music and I can confirm that this did fix the problem.

Thank you for your reply.
